name: Deploy FE-BE App

on:
  push:
    branches:
      - main

jobs:

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_BACKEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/fe-be
            git pull origin main
            cd nodejs-express-mysql
            npm install
            pkill node || true
            nohup node server.js > app.log 2>&1 &

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/fe-be
            git pull origin main
            cd frontend
            npm install
            npm run build
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r dist/* /usr/share/nginx/html/
            sudo systemctl restart nginx
